{% set name = "21cmFAST" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71e9f8dcdf44da474db27027beab1c6bd1d6fe78782df5782ec6e38ddc424c46


build:
  number: 2
  script: "INC=${PREFIX}/include LIB=${PREFIX}/lib {{ PYTHON }} -m pip install . -vv"
  skip: True  # [win]
  
requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - cffi
    - fftw
    - gsl
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - libblas
  run:
    - python
    - scipy
    - numpy
    - click
    - pyyaml
    - cffi >=1.0
    - scipy
    - astropy >=2.0
    - h5py >=2.8.0
    - cached-property
    - matplotlib-base
    - fftw
    - gsl

test:
  imports:
    - py21cmfast

about:
  home: https://github.com/21cmFAST/21cmFAST
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A semi-numerical cosmological simulation code for the 21cm signal
  description: |
    21cmFAST provides a simple and fast simulation package for the cosmological
    21cm signal as either coeval cubes or full lightcones.
  doc_url: https://21cmFAST.readthedocs.io/
  dev_url: https://github.com/21cmFAST/21cmFAST

extra:
  recipe-maintainers:
    - steven-murray
